# -*- coding: utf-8 -*-
"""YFinance_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APTenmAZtwPOXz7scnIghdxfZqRUh4l0
"""

import yfinance as yf
import numpy as np
import pandas as pd

def YahooData2returns(symbol):

    data = yf.download(symbol)
    prices = data.get('Adj Close', data.get('Close'))

    returns = prices [1:] / prices[:-1] - 1

    print(returns)